Added support for 'subvolume' config option
Signed-off-by: Karel Kočí <karel.koci@nic.cz>

diff --git a/scripts/srv.init b/scripts/srv.init
--- a/scripts/srv.init
+++ b/scripts/srv.init
@@ -40,12 +40,18 @@ start() {
 		mkdir -p /srv
 	fi
 
+	# Other subvolume?
+	config_get SUBVOL srv subvolume
+	if [ -z "${SUBVOL}" ]; then
+		SUBVOL='@'
+	fi
+
 	# Mount it
 	if [ "$(blkid "$DEV" -s TYPE -o value)" = ext4 ]; then
 		mount -t ext4 -o noatime "$DEV" /srv || die "Can't mount $DEV as /srv"
 		create_notification -n error "Your srv is ext4, you should convert to btrfs to enjoy all features"
 	else
-		mount -t btrfs -o subvol=@,noatime "$DEV" /srv || die "Can't mount $DEV as /srv"
+		mount -t btrfs -o subvol=${SUBVOL},noatime "$DEV" /srv || die "Can't mount $DEV as /srv"
 	fi
 
 	# Find root device
